
const size_t EMBEDQR_CAPWARN_SIZE = 14;
const char EMBEDQR_CAPWARN_COMPRESSED[] PROGMEM = "\x3D\x2D\x0A\xFB\x30\x7C\x3E\xC5\x55\x0C\x3C\xCD";

#define  EMBEDQR_CAPWARN       Decompress(EMBEDQR_CAPWARN_COMPRESSED,EMBEDQR_CAPWARN_SIZE).c_str()